### ISSUE TITLE
binderHelper.setOpenOnlyOne(true) is not working

### ISSUE THREAD

**Issue by idrisbohra** [hydrated/SwipeRevealLayout#14]
Hi @hydrated setOpenOnlyOne(true) is not working and to make it work need to do following changes on SwipeRevealLayout

 @Override
        public void onViewDragStateChanged(int state) {
            super.onViewDragStateChanged(state);
            final int prevState = mState;

            switch (state) {
                case ViewDragHelper.STATE_DRAGGING:
                    mState = STATE_DRAGGING;
                    break;

                case ViewDragHelper.STATE_IDLE:
                    if (mGlancing) {
                        mGlancing = false;
                        if(getHandler() != null) {
                            getHandler().postDelayed(new Runnable() {
                                @Override
                                public void run() {
                                    mDragHelper.smoothSlideViewTo(mMainView, mRectMainClose.left, mRectMainClose.top);
                                    ViewCompat.postInvalidateOnAnimation(SwipeRevealLayout.this);
                                }
                            }, DEAFULT_GLANCING_ANIMATION_PAUSE);
                        }
                        break;
                    }

                    // drag edge is left or right
                    /*change '(mDragEdge == DRAG_EDGE_LEFT || mDragEdge == DRAG_EDGE_RIGHT)'  to
                    '((mDragEdge & DRAG_EDGE_LEFT) > 0 || (mDragEdge & DRAG_EDGE_RIGHT) > 0)'*/

                    if ((mDragEdge & DRAG_EDGE_LEFT) > 0 || (mDragEdge & DRAG_EDGE_RIGHT) > 0) {
                        if (mMainView.getLeft() == mRectMainClose.left) {
                            mState = STATE_CLOSE;
                        } else {
                            mState = STATE_OPEN;
                        }
                    }

                    // drag edge is top or bottom
                    else {
                        if (mMainView.getTop() == mRectMainClose.top) {
                            mState = STATE_CLOSE;
                        } else {
                            mState = STATE_OPEN;
                        }
                    }
                    break;
            }

            if (mDragStateChangeListener != null && !mAborted && prevState != mState) {
                mDragStateChangeListener.onDragStateChanged(mState);
            }
        }

Thank you

**Comment by hydrated** [comment]
@idrisbohra Nice, would you like to create a P.R. to this repo?

**Comment by idrisbohra** [comment]
Hi @hydrated happy to do it
