### ISSUE TITLE
If Top and Bottom swipe also implemented in this branch it will be helpful to all

### ISSUE THREAD

**Issue by Vijayadhas** [hydrated/SwipeRevealLayout#19]
Wonderful work. But If Top and Bottom swipe also implemented in this branch it will be helpful to all. I used your https://github.com/chthai64/SwipeRevealLayout for swiping.. But I need left and right swipe in same view. you created this for that. But you said top and bottom is removed in this branch. If you add top and bottom swipe in this project it will be very helpful to all.

**Comment by hydrated** [comment]
Yeah, because the horizontal swiping and the vertical swiping are definitely conflicted at the same time. Either wrote an strict logic to control it at runtime. Or only allow one line at initialization.  

If I do have time to implement the feature. I probably start with only allow one line at the same time.

**Comment by Vijayadhas** [comment]
Super. If it is configurable like lockSwipe, setOpenOnlyOne.. It will very grateful to everyone..!! Thanks brother..

**Comment by Vijayadhas** [comment]
Brother.. While scroll recyclerview opened items getting closed automatically. How to fix this. Any idea please?

**Comment by hydrated** [comment]
@Vijayadhas The recyclerview has reused item machanism to save memory, so you should keep all states of your items in your model. And programmatically re-create all of your items by their states. 

It's irrelevant to this lib, check recyclerview for more information.

**Comment by Vijayadhas** [comment]
Ok brother. I just run this project. I got this issue. But your https://github.com/chthai64/SwipeRevealLayout demo project is working perfectly ji.. That's why asked ji..

**Comment by hydrated** [comment]
I am happy to announce that vertical drag edges has completed.

https://github.com/hydrated/SwipeRevealLayout/blob/master/art/ezgif-5-24e8a24b0876.gif
