### ISSUE TITLE
Problem with scrolling

### ISSUE THREAD

**Issue by IvanBegar** [hydrated/SwipeRevealLayout#24]
I am using your layout as part of row_item in RecyclerView in SwipeRefreshLayout. And when app:dragEdge="left|right" scrolling up/down doesn't work. Any suggestions?

**Comment by hydrated** [comment]
Thanks, It was due to the latest feature top|bottom bugs. It's been fixed.

Use the latest build.
**implementation 'com.github.hydrated:SwipeRevealLayout:cedd8e7'**
